deploy:
  staging:
    branch: staging
    commands:
      - npx shopify theme push --theme ${{ secrets.SHOPIFY_STAGING_THEME_ID }} --password ${{ secrets.SHOPIFY_STAGING_PASSWORD }} --store ${{ secrets.SHOPIFY_STAGING_STORE }}

  production:
    branch: production
    confirm: true
    commands:
      - npx shopify theme push --theme ${{ secrets.SHOPIFY_PRODUCTION_THEME_ID }} --password ${{ secrets.SHOPIFY_PRODUCTION_PASSWORD }} --store ${{ secrets.SHOPIFY_PRODUCTION_STORE }}
      - notify "Production deployment completed."

rollback:
  production:
    commands:
      - npx shopify theme push --theme ${{ secrets.SHOPIFY_BACKUP_THEME_ID }} --password ${{ secrets.SHOPIFY_BACKUP_PASSWORD }} --store ${{ secrets.SHOPIFY_BACKUP_STORE }}
      - notify "Rollback triggered. Restored previous theme."
