name: Development CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Remove Unwanted Files
        run: |
          rm -rf config/settings_data.json
          rm -rf templates/*.json
          git checkout -- config/settings_data.json templates/*.json

      - name: Install Dependencies
        run: npm install

      - name: Run Linting Checks
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Notify on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          message: "Development build failed. Check logs for details."
