name: Development CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Remove Unwanted Files
        run: |
          rm -rf config/settings_data.json
          rm -rf templates/*.json
          git checkout -- config/settings_data.json templates/*.json
