name: Verify Staging Before Production Deployment

on:
  pull_request:
    branches:
      - production
    types:
      - opened
      - synchronize

jobs:
  check-differences:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Staging and Production Branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compare Staging and Production
        run: |
          git fetch origin staging
          DIFF=$(git diff --name-status origin/staging..origin/production)
          if [ -n "$DIFF" ]; then
            echo "🚨 Code changes detected between staging and production."
            echo "$DIFF"
            exit 1
          fi

      - name: Approve Merge if No Differences
        run: |
          echo "✅ Staging matches production. Safe to merge."
