name: Staging Deployment

on:
  pull_request:
    branches:
      - staging

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Staging Branch
        uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Add Development Remote
        run: |
          git remote add development https://github.com/${{ github.repository }}.git
          git fetch development development

      - name: Merge Development into Staging (Exclude Unwanted Files)
        run: |
          git merge development/development --no-ff --no-edit || echo "Merge conflicts detected."
          git checkout --ours config/settings_data.json templates/*.json

      - name: Push Merged Changes
        run: |
          git push origin staging || echo "Push failed. Manual conflict resolution required."

  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Theme Preview Link
        env:
          SHOPIFY_STAGING_STORE: ${{ secrets.SHOPIFY_STAGING_STORE }}
        run: |
          echo "Staging preview: https://${SHOPIFY_STAGING_STORE}?preview_theme_id=${{ secrets.SHOPIFY_STAGING_THEME_ID }}"
